### ISSUE TITLE
In the event of a disconnection Twirc stops working correctly

### ISSUE THREAD

**Issue by pwr22** [semifor/twirc#16]
The twitter stream seems to timeout and then Twirc does not attempt to re-establish a connection

-tweeter/&twitter- Twitter stream error: timeout
-tweeter/&twitter- Twitter stream error: Connection timed out

**Comment by semifor** [comment]
This seems to be fixed in the 0.18-TRIAL. We can reopen if we run into it again.

I did make changes that would definitely address this, but have no idea how to craft a good test for it. :-/
